name: Build and Release Bazel Target

on:
  push:
    branches:
      - 'cdleary/2024-05-28-crate-dso-branch'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Bazel
      uses: actions/setup-bazel@v1
      with:
        bazel-version: '6.5.0' # Specify the Bazel version you need

    - name: Build Bazel target
      run: |
        bazel build -c opt //xls/public:libxls.dylib

    - name: Create artifact directory
      run: mkdir -p artifacts

    - name: Copy Bazel target to artifacts
      run: cp -r bazel-bin/xls/public/libxls.dylib artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bazel-target
        path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: bazel-target
        path: artifacts

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/libxls.dylib
        asset_name: libxls.dylib
        asset_content_type: application/x-sharedlib

